# Generated by Django 2.0.5 on 2018-06-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180618_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(max_length=250),
        ),
    ]
