# Generated by Django 2.0.6 on 2018-06-29 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('latlong', models.CharField(max_length=48)),
                ('phone', models.CharField(max_length=48)),
                ('branch', models.CharField(max_length=32)),
                ('driver', models.CharField(max_length=8)),
                ('route', models.CharField(max_length=8)),
                ('tanktype', models.CharField(max_length=8)),
                ('tanknumber', models.CharField(max_length=32)),
                ('tanksize', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filenameonly', models.CharField(max_length=255)),
                ('filefullpath', models.CharField(max_length=255)),
                ('filefolderonly', models.CharField(max_length=255)),
                ('summary_file', models.CharField(max_length=255)),
                ('count_accounts', models.IntegerField()),
                ('count_deliveries', models.IntegerField()),
                ('count_locations', models.IntegerField()),
                ('count_loads', models.IntegerField()),
                ('count_blankaccounts', models.IntegerField()),
                ('count_blankloads', models.IntegerField()),
                ('file_version', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivernumber', models.CharField(max_length=8)),
                ('routenumber', models.CharField(max_length=8)),
                ('trucknumber', models.CharField(max_length=8)),
                ('startdate', models.DateTimeField()),
                ('finishdate', models.DateTimeField()),
                ('starttotalizer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finishtotalizer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percent_full_start', models.IntegerField()),
                ('percent_full_end', models.IntegerField()),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('productcode', models.CharField(max_length=8)),
                ('productdesc', models.CharField(max_length=128)),
                ('ticketnumber', models.CharField(max_length=16)),
                ('salenumber', models.CharField(max_length=16)),
                ('registernumber', models.IntegerField()),
                ('registerserialnumber', models.CharField(max_length=16)),
                ('registertype', models.CharField(max_length=16)),
                ('tempcompensated', models.CharField(max_length=8)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('latlong', models.CharField(max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='importer.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivernumber', models.CharField(max_length=8)),
                ('routenumber', models.CharField(max_length=8)),
                ('trucknumber', models.CharField(max_length=8)),
                ('localdate', models.DateTimeField()),
                ('notes', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('latlong', models.CharField(max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_previous', to='importer.Account')),
                ('origin_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_next', to='importer.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('truckinspectiondate', models.DateTimeField()),
                ('tankinspectiondate', models.DateTimeField()),
                ('watercapacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('passwordhash_decoded', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='importer.Truck'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='importer.Truck'),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_imports', to='importer.User'),
        ),
    ]
